### create a transction

POST http://localhost:8000/api/v1/transactions
Content-Type: application/json

{
    "description": "Groceries",
    "amount": 45.50,
    "type": "expense"
    }


### get all Transaction

GET http://localhost:8000/api/v1/transactions


### Update a transaction ( replace _id with a real one after creating )

PATCH http://localhost:8000/api/v1/transactions
Content-Type:  application/json

{
    "_id" : "6a9261c82249dbded1bd8b84",
    "amount":50
}


#### Delete a transaction ( replace _ id with a real one)

DELETE http://localhost:8000/api/v1/transactions/6a9261c82249dbded1bd8b84



#### SignUp a new User

POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "name" : "Milan",
    "email": "milan@test.com",
    "password" : "password123"
}

#### Login a user 

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "milan@test.com",
    "password" : "password123"
}